---
title: "hw5"
author: "Nihan Gencerliler"
date: "11/9/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(readxl)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 16, 
  fig.height = 12,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

```{r}

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

replace_missing = function(original_value) {
  if ((is.numeric(original_value)) & (is.na(original_value))) 
   {new_value=mean(original_value)}
  else if ((is.character(original_value)) & (is.na(original_value)))
    {new_value="virginica"}
  else {new_value=original_value}
  new_value
}

test_df = replace_missing(iris_with_missing)
test_df

```

For numeric variables, you should fill in missing values with the mean of non-missing values
For character variables, you should fill in missing values with "virginica"

